# 多个goroutine 协作，共同进退

- 地址 https://github.com/oklog/run
- prometheus 采用的

## 用法

- g.add 第一个参数为run函数，返回error，要求改函数长时间运行，遇到错误再退出
  - 具体场景有两个1. for +ticker +ctx
  - 长时间运行的 http 和rpc 用error chan 在g.add中做
- 第二个参数为interrupt函数，作用是退出时做一些清理操作

## 在server.go main 中添加如下代码

- 接收退出信号的函数

```go
	// 编排开始
	var g run.Group
	ctxAll, cancelAll := context.WithCancel(context.Background())
	fmt.Println(ctxAll)
	{

		// 处理信号退出的handler
		term := make(chan os.Signal, 1)
		signal.Notify(term, os.Interrupt, syscall.SIGTERM)
		cancelC := make(chan struct{})
		g.Add(
			func() error {
				select {
				case <-term:
					level.Warn(logger).Log("msg", "Receive SIGTERM ,exiting gracefully....")
					cancelAll()
					return nil
				case <-cancelC:
					level.Warn(logger).Log("msg", "other cancel exiting")
					return nil
				}
			},
			func(err error) {
				close(cancelC)
			},
		)
	}
	g.Run()
```

> 这时运行我们的server ，点击停止可以看到

```shell
level=info ts=2021-07-30T11:03:55.821+08:00 caller=server.go:93 msg=successfully_init_db db_num=1
level=warn ts=2021-07-30T11:03:59.122+08:00 caller=server.go:112 msg="Received SIGTERM, exiting gracefully..."



```

- 退出的时候通知其他goroutine 退出，在ctxAll watch的
- 只要有任意的Add 函数报错了，逐一执行他们的interrupt函数，否则等待第一个err返回

### 添加一个模块1，看一下协同的效果

```go
	{

		g.Add(func() error {
			for {
				ticker := time.NewTicker(5 * time.Second)
				select {
				case <-ctxAll.Done():
					level.Warn(logger).Log("msg", "我是模块01退出了，接收到了cancelall")
					return nil
				case <-ticker.C:
					level.Warn(logger).Log("msg", "我是模块01")
				}

			}

		}, func(err error) {

		},
		)
	}

```